steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, -t, ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/enterprise-conversational-ai:$COMMIT_SHA, .]
  - name: gcr.io/cloud-builders/docker
    args: [push, ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/enterprise-conversational-ai:$COMMIT_SHA]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [run, deploy, enterprise-conversational-ai, --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/enterprise-conversational-ai:$COMMIT_SHA, --region=${_REGION}, --platform=managed]
substitutions:
  _REGION: europe-west2
  _REPOSITORY: apps
options:
  logging: CLOUD_LOGGING_ONLY
